### ISSUE TITLE
Heavy CPU load?

### ISSUE THREAD

**Issue by aurnik** [L-B-X/LBX-SRD-Smart-Knobs#2]
@L-B-X Hey, I'm not sure what's happening but whenever I run this script Reaper slows down tremendously and the script opens up the ReaScript Console Output. The lag is to the point where I'll turn a controller knob and I'll see the parameter update a full second later. Closing this script returns performance back to normal. Any idea what might be causing this? I'm happy to work on a fix myself and submit it back to you as a PR.

**Comment by L-B-X** [comment]
@aurnik  Does anything appear in the console window?

Not had any other reports like this - just noticed you closed it?  Have you solved the issue?

**Comment by aurnik** [comment]
@L-B-X Yes there's quite a bit in the console window, I think the lag is actually being caused by the script getting caught in a loop sending feedback. Apologize for the confusion, and thanks for the quick response

Turns out this was an issue with ReaLearn (or I guess both). In ReaLearn, DON'T uncheck "Send feedback only if track armed"

**Comment by aurnik** [comment]
So now I'm not sure what the cause is but with more testing it appears that it is an issue with this script and the problem wasn't from the ReaLearn setting I was referring to. It most recently happened when switching between two FX chains (both just had ReaEQ) where one ReaEQ worked and the other was lagging. I just removed and re-added the lagging one and it worked.
I don't know if anything was actually solved, but it's at least working right now

**Comment by L-B-X** [comment]
What sort of info was in the console window - that may help to identify the problem.  If stuff is being printed into the console window - it will seriously lag Reaper.  The console window always does this - so find the cause of why whichever script is filling the console window - and you probably have the culprit.  I don't use Realearn - but if you can post some of the console output if it happens again - I can at least tell you whether it is Smart Knobs or not producing it.

**Comment by aurnik** [comment]
Hey @L-B-X I've been testing since originally opening the issue and haven't been able to replicate the original problem. So while I don't know what was causing the console problem, I appreciate you giving me the heads up about the console lag.

Don't want to open another issue but on a different note, this script has been incredibly useful and has made me reevaluate the usefulness and possibilities of my midi controller. Is there any way to send additional MIDI messages back to the controller when switching between modules? I ask because it's already great that my controller is now updating values based on the focused plugin, and it would be even more useful if I could also send messages to change the colors of each knob when switching focused plugins to really have a fully custom layout for each plugin. If you can point me in the right direction I'd be happy to contribute this functionality as a PR.
